config/routes.rb
Rails.application.routes.draw do

  get 'user_browser/index'

  resources :monthly_self_examinations
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: "home#index"

  get 'dashboard/:id/show' => "dashboard#show", as: "dashboard_show"

  get "student/:id/index" => "monthly_self_examinations#student_index", as: "student_index"
  get "teacher/:id/menu" => "students#menu", as: "student_menu"

  get "role_manager/index" => "role_manager#index", as: "role_manager"
  get "role_manager/:id/edit" => "role_manager#edit", as: "edit_role_manager"
  patch "role_manager/index/:id/:role" => "role_manager#update_role", as: "role_manager_update_role"

  get "links_manager/index" => "links_manager#index", as: "links_manager"
  get "links_manager/:id/edit_teacher" => "links_manager#edit_teacher", as: "links_manager_edit_teacher"
  patch "links_manager/index/:id/:teacher_id/update_teacher" => "links_manager#update_teacher", as: "links_manager_update_teacher"

  get "links_manager/:id/edit_tutor" => "links_manager#edit_tutor", as: "links_manager_edit_tutor"
  patch "links_manager/index/:id/:tutor_id/update_tutor" => "links_manager#update_tutor", as: "links_manager_update_tutor"

end

app/models/monthly_self_examination.rb
# == Schema Information
#
# Table name: monthly_self_examinations
#
#  id              :integer          not null, primary key
#  periode         :string
#  what_ive_done   :string
#  what_ive_learnt :string
#  what_ive_felt   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#

class MonthlySelfExamination < ActiveRecord::Base
  belongs_to :user
end

app/controllers/monthly_self_examinations_controller.rb
class MonthlySelfExaminationsController < ApplicationController
    before_action :set_monthly_self_examination, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    # GET /monthly_self_examinations
    # GET /monthly_self_examinations.json
    def index
      @users = User.all
      if current_user.has_role? :student
        @monthly_self_examinations = MonthlySelfExamination.where(user_id: current_user.id)
      elsif current_user.has_role? :teacher
        @monthly_self_examinations = MonthlySelfExamination.where(user_id: User.where(teacher_id: current_user.id))
      elsif current_user.has_role? :tutor
        @monthly_self_examinations = MonthlySelfExamination.where(user_id: User.where(tutor_id: current_user.id))
      else
        @monthly_self_examinations = MonthlySelfExamination.all
      end
    end

    # GET /monthly_self_examinations/1
    # GET /monthly_self_examinations/1.json
    def show
    end

    def student_index
      @student = User.find(params[:id])
      @student_examinations = MonthlySelfExamination.where(user_id: @student.id)
    end

    # GET /monthly_self_examinations/new
    def new
        @monthly_self_examination = MonthlySelfExamination.new
    end

    # GET /monthly_self_examinations/1/edit
    def edit
    end

    # POST /monthly_self_examinations
    # POST /monthly_self_examinations.json
    def create
        if user_signed_in?
            @monthly_self_examination = MonthlySelfExamination.new(monthly_self_examination_params)
            @monthly_self_examination.user = current_user
        end

        respond_to do |format|
            if @monthly_self_examination.save
                format.html { redirect_to @monthly_self_examination, notice: 'Votre auto-évaluation a bien été créée.' }
                format.json { render :show, status: :created, location: @monthly_self_examination }
            else
                format.html { render :new }
                format.json { render json: @monthly_self_examination.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /monthly_self_examinations/1
    # PATCH/PUT /monthly_self_examinations/1.json
    def update
        respond_to do |format|
            if @monthly_self_examination.update(monthly_self_examination_params)
                format.html { redirect_to @monthly_self_examination, notice: 'Votre auto-évaluation a bien été mise à jour.' }
                format.json { render :show, status: :ok, location: @monthly_self_examination }
            else
                format.html { render :edit }
                format.json { render json: @monthly_self_examination.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /monthly_self_examinations/1
    # DELETE /monthly_self_examinations/1.json
    def destroy
        @monthly_self_examination.destroy
        respond_to do |format|
            format.html { redirect_to monthly_self_examinations_url, notice: 'Votre auto-évaluation a bien été supprimée.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_monthly_self_examination
        @monthly_self_examination = MonthlySelfExamination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monthly_self_examination_params
        params.require(:monthly_self_examination).permit(:periode, :what_ive_done, :what_ive_learnt, :what_ive_felt)
    end
end

app/views/monthly_self_examinations/_form.html.erb
<%= form_for(@monthly_self_examination) do |f| %>
  <% if @monthly_self_examination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monthly_self_examination.errors.count, "error") %> prohibited this monthly_self_examination from being saved:</h2>

      <ul>
      <% @monthly_self_examination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :periode, "Période" %><br>
    <%= f.text_field :periode, class: "form-control" %>
  </div><br>
  <div class="field">
    <%= f.label :what_ive_done, "Ce que j'ai fais" %><br>
    <%= f.text_area :what_ive_done, class: "form-control" %>
  </div><br>
  <div class="field">
    <%= f.label :what_ive_learnt, "Ce que j'ai appris" %><br>
    <%= f.text_area :what_ive_learnt, class: "form-control" %>
  </div><br>
  <div class="field">
    <%= f.label :what_ive_felt, "Ce que j'ai ressenti" %><br>
    <%= f.text_area :what_ive_felt, class: "form-control" %>
  </div><br>
  <div class="actions">
    <%= f.submit "Enregister", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/monthly_self_examinations/edit.html.erb
<div class="page-headers">
    <h1>Modifier auto-évaluation</h1>
</div>

<%= render 'form' %>

<%= link_to 'Retour', monthly_self_examinations_path, class: "btn btn-warning" %>

app/views/monthly_self_examinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auto-évaluations mensuelles</h1>
<% if current_user.has_role? :student %>
   <%= link_to 'Créer une nouvelle auto-évaluation', new_monthly_self_examination_path, class: "btn btn-info btn-lg" %>
<% end %>

<table class="table">
    <thead>
        <tr>
            <th>
                <h4>Nom de l'élève</h4>
            </th>
            <th>
                <h4>Période</h4>
            </th>
            <th>
                <h4>Ce que j'ai fait</h4>
            </th>
            <th>
                <h4>Ce que j'ai appris</h4>
            </th>
            <th>
                <h4>Ce que j'ai ressenti</h4>
            </th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @monthly_self_examinations.each do |monthly_self_examination| %>
        <tr>
            <% student = @users.find(monthly_self_examination.user_id)%>
            <% student_name = get_user_full_name(monthly_self_examination.user_id) %>
            <td><%= link_to student_name, student_index_path(student.id), class: "btn btn-success btn-lg" %></td>
            <td><%= monthly_self_examination.periode %></td>
            <td><%= monthly_self_examination.what_ive_done %></td>
            <td><%= monthly_self_examination.what_ive_learnt %></td>
            <td><%= monthly_self_examination.what_ive_felt %></td>
            <td><%= link_to 'Voir', monthly_self_examination , class: "btn btn-primary"%></td>

            <%if current_user.has_role? :student %>
              <td><%= link_to 'Modifier', edit_monthly_self_examination_path(monthly_self_examination), class: "btn btn-warning" %></td>
              <td><%= link_to 'Supprimer', monthly_self_examination, method: :delete, data: { confirm: 'Êtes-vous sûr(e) ?' }, class: "btn btn-danger" %></td>
            <%end%>

        </tr>
        <% end %>
    </tbody>
</table>
<br>

app/views/monthly_self_examinations/new.html.erb
<h1>Auto-évaluations mensuelles</h1>

<%= render 'form' %>

<%= link_to 'Retour', monthly_self_examinations_path %>

app/views/monthly_self_examinations/show.html.erb
<div class="page-header">
  <h2><%= get_user_full_name(@monthly_self_examination.user_id) %></h2>
    <h3>Période :
        <small><%= @monthly_self_examination.periode %></small>
    </h3>
</div>

<p>
    <h4>Ce que j'ai fait :</h4>
    <%= @monthly_self_examination.what_ive_done %>
</p>
<hr>
<p>
    <h4>Ce que j'ai appris :</h4>
    <%= @monthly_self_examination.what_ive_learnt %>
</p>
<hr>
<p>
    <h4>Ce que j'ai ressenti :</h4>
    <%= @monthly_self_examination.what_ive_felt %>
</p>
<hr>
<% if @monthly_self_examination.user_id == current_user.id %>
<%= link_to 'Modifier', edit_monthly_self_examination_path(@monthly_self_examination), class: "btn btn-warning" %>
<% end %>
<%= link_to 'Retour', monthly_self_examinations_path, class: "btn btn-danger" %>
<%= link_to 'Imprimer', '#', :onclick => 'window.print();return false;', class: "btn btn-success"%>

app/views/monthly_self_examinations/student_index.html.erb
<p id="notice"><%= notice %></p>
<% student_name = @student.first_name + ' ' + @student.last_name %>
<div class="page-header">
    <h1>Auto-évaluations mensuelles de <%= student_name %></h1>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                <h4>Période</h4>
            </th>
            <th>
                <h4>Ce que j'ai fait</h4>
            </th>
            <th>
                <h4>Ce que j'ai appris</h4>
            </th>
            <th>
                <h4>Ce que j'ai ressenti</h4>
            </th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @student_examinations.each do |monthly_self_examination| %>
        <tr>
            <td><%= monthly_self_examination.periode %></td>
            <td><%= monthly_self_examination.what_ive_done %></td>
            <td><%= monthly_self_examination.what_ive_learnt %></td>
            <td><%= monthly_self_examination.what_ive_felt %></td>
            <td><%= link_to 'Voir', monthly_self_examination , class: "btn btn-primary"%></td>

            <%if current_user.has_role? :student %>
            <td><%= link_to 'Modifier', edit_monthly_self_examination_path(monthly_self_examination), class: "btn btn-warning" %></td>
            <td><%= link_to 'Supprimer', monthly_self_examination, method: :delete, data: { confirm: 'Êtes-vous sûr(e) ?' }, class: "btn btn-danger" %></td>
            <%end%>

        </tr>
        <% end %>
    </tbody>
</table>
<br>