config/routes.rb
Rails.application.routes.draw do

  get 'user_browser/index'

  resources :monthly_self_examinations
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: "home#index"

  get 'dashboard/:id/show' => "dashboard#show", as: "dashboard_show"

  get "student/:id/index" => "monthly_self_examinations#student_index", as: "student_index"
  get "teacher/:id/menu" => "students#menu", as: "student_menu"

  get "role_manager/index" => "role_manager#index", as: "role_manager"
  get "role_manager/:id/edit" => "role_manager#edit", as: "edit_role_manager"
  patch "role_manager/index/:id/:role" => "role_manager#update_role", as: "role_manager_update_role"

  get "links_manager/index" => "links_manager#index", as: "links_manager"
  get "links_manager/:id/edit_teacher" => "links_manager#edit_teacher", as: "links_manager_edit_teacher"
  patch "links_manager/index/:id/:teacher_id/update_teacher" => "links_manager#update_teacher", as: "links_manager_update_teacher"

  get "links_manager/:id/edit_tutor" => "links_manager#edit_tutor", as: "links_manager_edit_tutor"
  patch "links_manager/index/:id/:tutor_id/update_tutor" => "links_manager#update_tutor", as: "links_manager_update_tutor"

end

app/controllers/links_manager_controller.rb
class LinksManagerController < ApplicationController
  before_action :authenticate_user!
  def index
    @students = User.with_role :student
  end

  def edit_tutor
    @tutors = User.with_role :tutor
    @student_focused = User.find(params[:id])
  end

  def edit_teacher
    @teachers = User.with_role :teacher
    @student_focused = User.find(params[:id])
  end

  def update_teacher
    user_focused = User.find(params[:id])
    user_focused.teacher_id = params[:teacher_id]
    respond_to do |format|
        if user_focused.save
            format.html { redirect_to links_manager_path, notice: 'Le professeur de ' + get_user_full_name(user_focused) + ' a bien été modifié.' }
            format.json { render :show, status: :created, location: links_manager_path }
        else
            format.html { redirect_to links_manager_path, notice: 'Erreur'}
            format.json { render json: user_focused.errors, status: :unprocessable_entity }
        end
    end
  end

  def update_tutor
    user_focused = User.find(params[:id])
    user_focused.tutor_id = params[:tutor_id]
    respond_to do |format|
        if user_focused.save
            format.html { redirect_to links_manager_path, notice: 'Le tuteur de ' + get_user_full_name(user_focused) + ' a bien été modifié.' }
            format.json { render :show, status: :created, location: links_manager_path }
        else
            format.html { render :new }
            format.json { render json: user_focused.errors, status: :unprocessable_entity }
        end
    end
  end
end

app/views/links_manager/edit_teacher.html.erb
<div class="page-header">
  <h1>Modifier le professeur pour <%= get_user_full_name(@student_focused) %></h1>
</div>

<h3>Choisissez un nouveau professeur parmi la liste :</h3>

<% @teachers.each do |teacher| %>
<%= link_to get_user_full_name(teacher), links_manager_update_teacher_path(@student_focused, teacher), method: :patch, class: "btn btn-danger btn-lg" %>
<% end %>

app/views/links_manager/edit_tutor.html.erb
<div class="page-header">
  <h1>Modifier le tuteur pour <%= get_user_full_name(@student_focused) %></h1>
</div>

<h3>Choisissez un nouveau tuteur parmi la liste :</h3>

<% @tutors.each do |tutor| %>
<%= link_to get_user_full_name(tutor), links_manager_update_tutor_path(@student_focused, tutor), method: :patch, class: "btn btn-danger btn-lg" %>
<% end %>

app/views/links_manager/index.html.erb
<div class="page-header">
    <h1>
        Gestion des liens
        <small>Cliquez pour modifier</small>
    </h1>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                <h3>Etudiant</h3>
            </th>
            <th>
                <h3>Professeur</h3>
            </th>
            <th>
                <h3>Tuteur</h3>
            </th>
        </tr>
    </thead>

    <tbody>
        <% @students.each do |student| %>
        <tr>
            <%
            if student.tutor_id != nil
              tutor = User.find(student.tutor_id)
            end
            if student.teacher_id != nil
               teacher = User.find(student.teacher_id)
            end
            %>
            <td>
                <h4><%= get_user_full_name(student) %></h4>
            </td>
            <td>
                <% if student.teacher_id != nil %>
                  <%= link_to get_user_full_name(teacher), links_manager_edit_teacher_path(student), class: "btn btn-warning btn-lg" %>
                <% else %>
                  <%= link_to "Aucun", links_manager_edit_teacher_path(student), class: "btn btn-default btn-lg" %>
                <% end %>
            </td>
            <td>
                <% if student.tutor_id != nil %>
                  <%= link_to get_user_full_name(tutor), links_manager_edit_tutor_path(student), class: "btn btn-danger btn-lg" %>
                <% else %>
                  <%= link_to "Aucun", links_manager_edit_tutor_path(student), class: "btn btn-default btn-lg" %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>