config/routes.rb
Rails.application.routes.draw do

  get 'user_browser/index'

  resources :monthly_self_examinations
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: "home#index"

  get 'dashboard/:id/show' => "dashboard#show", as: "dashboard_show"

  get "student/:id/index" => "monthly_self_examinations#student_index", as: "student_index"
  get "teacher/:id/menu" => "students#menu", as: "student_menu"

  get "role_manager/index" => "role_manager#index", as: "role_manager"
  get "role_manager/:id/edit" => "role_manager#edit", as: "edit_role_manager"
  patch "role_manager/index/:id/:role" => "role_manager#update_role", as: "role_manager_update_role"

  get "links_manager/index" => "links_manager#index", as: "links_manager"
  get "links_manager/:id/edit_teacher" => "links_manager#edit_teacher", as: "links_manager_edit_teacher"
  patch "links_manager/index/:id/:teacher_id/update_teacher" => "links_manager#update_teacher", as: "links_manager_update_teacher"

  get "links_manager/:id/edit_tutor" => "links_manager#edit_tutor", as: "links_manager_edit_tutor"
  patch "links_manager/index/:id/:tutor_id/update_tutor" => "links_manager#update_tutor", as: "links_manager_update_tutor"

end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-custom">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Accueil", root_path, class: 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <!-- Left side of navbar -->
            <% if user_signed_in? and (current_user.has_role? :tutor or current_user.has_role? :teacher) %>
            <%= render "common/navbar_teacher_tutor" %>
            <% end %>
            <% if user_signed_in? and current_user.has_role? :student %>
            <%= render "common/navbar_student" %>
            <% end %>
            <% if user_signed_in? and current_user.has_role? :admin %>
            <%= render "common/navbar_admin" %>
            <% end %>

            <ul class="nav navbar-nav navbar-right">

                <% if user_signed_in? %>
                <li class="active">
                    <a href="#"><%= get_role_string %></a>
                </li>
                <li><%= link_to current_user.first_name + " " + current_user.last_name, edit_user_registration_path %></li>
                <li><%= link_to destroy_user_session_path, method: :delete do %>
                    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                    <% end %></li>
            <% else %>
                <li><%= link_to "Se connecter", new_user_registration_path %></li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/common/_navbar_admin.html.erb
<ul class="nav navbar-nav">
    <li>
        <%= link_to "Gestion des rôles", role_manager_path %>
    </li>
    <li>
        <%= link_to "Gestion des liens", links_manager_path %>
    </li>
</ul>

app/views/common/_navbar_student.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to "Dashboard", dashboard_show_path(current_user.id) %></li>
  <li><%= link_to "Auto-Evaluations", monthly_self_examinations_path%></li>
</ul>

app/views/common/_navbar_teacher_tutor.html.erb
<ul class="nav navbar-nav">
  <li><li><%= link_to "Dashboard", dashboard_show_path(current_user.id) %></li></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mes élèves<span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <% get_student_list.each do |student| %>
            <li><%= link_to get_user_full_name(student), student_menu_path(student.id) %></li>
          <% end %>
        </ul>
    </li>
</ul>